/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.OrganBankCoordinatorRole;

import HealthCentre.DB4OUtil.DB4OUtil;
import HealthCentre.EcoSystem;
import HealthCentre.Enterprise.Enterprise;
import HealthCentre.Network.Network;
import HealthCentre.Organization.OrganBankOrganization;
import HealthCentre.UserAccount.UserAccount;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import static javax.swing.SwingUtilities.getWindowAncestor;

/**
 *
 * @author romiltiwari
 */
public class OrganBankCoordinatorWorkAreaJPanel extends javax.swing.JPanel {

    private EcoSystem ecoSystem;
    private Network network;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    boolean index = true;
    private UserAccount userAccount;
    private OrganBankOrganization organBankOrganisation;
    private Enterprise enterprise;

    /**
     * Creates new form OrganBankCoordinatorWorkAreaJPanel
     */
    public OrganBankCoordinatorWorkAreaJPanel(UserAccount account,
            OrganBankOrganization organBankOrganisation, Enterprise enterprise,
            EcoSystem business, Network network) {
        initComponents();
        this.userAccount = account;
        this.organBankOrganisation = organBankOrganisation;
        this.enterprise = enterprise;
        this.ecoSystem = business;
        this.network = network;
    }

    /**
     * Description : Color Change on Click Handling
     *
     * @param hover
     * @param random
     */
    public void colorChangeOnClick(JPanel hover, Color random) {
        hover.setBackground(random);
    }

    /**
     * Description : Handle Menu Click and set background accordingly.
     *
     * @param hideMenu1
     * @param hideMenu2
     * @param number
     */
    public void menuClickHandling(JPanel hideMenu1, JPanel hideMenu2, int number) {
        if (number == 1) {
            hideMenu1.setBackground(new Color(70, 55, 37));
            hideMenu2.setBackground(new Color(216, 99, 1));
        } else {
            hideMenu1.setBackground(new Color(216, 99, 1));
            hideMenu2.setBackground(new Color(70, 55, 37));
        }
    }

    /**
     * Description : Change Image on Click Handling
     *
     * @param labelButton
     * @param resourceImage
     */
    public void imageChangeOnClick(JLabel labelButton, String resourceImage) {
        ImageIcon aimg = new ImageIcon(getClass().getResource(resourceImage));
        labelButton.setIcon(aimg);
    }

    /**
     * Description : Menu Hide/Show Handling on Click even.
     *
     * @param showHideMenu
     * @param board
     * @param labelButton
     */
    public void showHideMenuHandling(JPanel showHideMenu, boolean board, JLabel labelButton) {
        if (board == true) {
            showHideMenu.setPreferredSize(new Dimension(50,
                    showHideMenu.getHeight()));
            imageChangeOnClick(labelButton, "/Images_1/menu-bar.png");
        } else {
            showHideMenu.setPreferredSize(new Dimension(270,
                    showHideMenu.getHeight()));
            imageChangeOnClick(labelButton, "/Images_1/menu-bar.png");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        ButtonMinMaxClose = new javax.swing.JPanel();
        CloseButton = new javax.swing.JPanel();
        closeButtonLabel = new javax.swing.JLabel();
        BtnMax = new javax.swing.JPanel();
        maxButtonLabel = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        menuIcon = new javax.swing.JPanel();
        linehidemenu = new javax.swing.JPanel();
        hidemenu = new javax.swing.JPanel();
        hideMenuButtonLabel = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        profileButtonLabel = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        manageRequestsButtonLabel = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        backLabel = new javax.swing.JLabel();
        userProcessContainer = new javax.swing.JPanel();

        setBackground(new java.awt.Color(199, 247, 247));
        setLayout(new java.awt.BorderLayout());

        Header.setBackground(new java.awt.Color(15, 29, 52));
        Header.setPreferredSize(new java.awt.Dimension(800, 50));
        Header.setLayout(new java.awt.BorderLayout());

        ButtonMinMaxClose.setBackground(new java.awt.Color(0, 0, 0));
        ButtonMinMaxClose.setPreferredSize(new java.awt.Dimension(150, 50));

        CloseButton.setBackground(new java.awt.Color(15, 29, 52));
        CloseButton.setPreferredSize(new java.awt.Dimension(50, 50));

        closeButtonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeButtonLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete_32px.png"))); // NOI18N
        closeButtonLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeButtonLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeButtonLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout CloseButtonLayout = new javax.swing.GroupLayout(CloseButton);
        CloseButton.setLayout(CloseButtonLayout);
        CloseButtonLayout.setHorizontalGroup(
            CloseButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 57, Short.MAX_VALUE)
            .addGroup(CloseButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(closeButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
        );
        CloseButtonLayout.setVerticalGroup(
            CloseButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(CloseButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(closeButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        BtnMax.setBackground(new java.awt.Color(15, 29, 52));
        BtnMax.setPreferredSize(new java.awt.Dimension(50, 50));

        maxButtonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maxButtonLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/full_screen_32px.png"))); // NOI18N
        maxButtonLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        maxButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maxButtonLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maxButtonLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maxButtonLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BtnMaxLayout = new javax.swing.GroupLayout(BtnMax);
        BtnMax.setLayout(BtnMaxLayout);
        BtnMaxLayout.setHorizontalGroup(
            BtnMaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 58, Short.MAX_VALUE)
            .addGroup(BtnMaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(maxButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE))
        );
        BtnMaxLayout.setVerticalGroup(
            BtnMaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(BtnMaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(maxButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout ButtonMinMaxCloseLayout = new javax.swing.GroupLayout(ButtonMinMaxClose);
        ButtonMinMaxClose.setLayout(ButtonMinMaxCloseLayout);
        ButtonMinMaxCloseLayout.setHorizontalGroup(
            ButtonMinMaxCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonMinMaxCloseLayout.createSequentialGroup()
                .addContainerGap(875, Short.MAX_VALUE)
                .addComponent(BtnMax, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ButtonMinMaxCloseLayout.setVerticalGroup(
            ButtonMinMaxCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(BtnMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        Header.add(ButtonMinMaxClose, java.awt.BorderLayout.CENTER);

        add(Header, java.awt.BorderLayout.PAGE_START);

        menu.setLayout(new java.awt.BorderLayout());

        menuIcon.setBackground(new java.awt.Color(0, 0, 0));
        menuIcon.setPreferredSize(new java.awt.Dimension(50, 500));
        menuIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        linehidemenu.setBackground(new java.awt.Color(15, 29, 52));

        javax.swing.GroupLayout linehidemenuLayout = new javax.swing.GroupLayout(linehidemenu);
        linehidemenu.setLayout(linehidemenuLayout);
        linehidemenuLayout.setHorizontalGroup(
            linehidemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        linehidemenuLayout.setVerticalGroup(
            linehidemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        menuIcon.add(linehidemenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 10));

        hidemenu.setBackground(new java.awt.Color(15, 29, 52));
        hidemenu.setPreferredSize(new java.awt.Dimension(50, 50));

        hideMenuButtonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hideMenuButtonLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back_32px.png"))); // NOI18N
        hideMenuButtonLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hideMenuButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hideMenuButtonLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hideMenuButtonLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hideMenuButtonLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout hidemenuLayout = new javax.swing.GroupLayout(hidemenu);
        hidemenu.setLayout(hidemenuLayout);
        hidemenuLayout.setHorizontalGroup(
            hidemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
            .addGroup(hidemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(hidemenuLayout.createSequentialGroup()
                    .addComponent(hideMenuButtonLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        hidemenuLayout.setVerticalGroup(
            hidemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(hidemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(hideMenuButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        menuIcon.add(hidemenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, -1));

        menu.add(menuIcon, java.awt.BorderLayout.LINE_START);

        jPanel4.setBackground(new java.awt.Color(31, 31, 31));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(31, 31, 31));

        profileButtonLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        profileButtonLabel.setForeground(new java.awt.Color(255, 255, 255));
        profileButtonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        profileButtonLabel.setText("Profile");
        profileButtonLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        profileButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileButtonLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(profileButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(profileButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel4.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 220, 50));

        jPanel11.setBackground(new java.awt.Color(31, 31, 31));

        manageRequestsButtonLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        manageRequestsButtonLabel.setForeground(new java.awt.Color(255, 255, 255));
        manageRequestsButtonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        manageRequestsButtonLabel.setText("Manage Requests");
        manageRequestsButtonLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        manageRequestsButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                manageRequestsButtonLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(manageRequestsButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(manageRequestsButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel4.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        jPanel12.setBackground(new java.awt.Color(31, 31, 31));

        backLabel.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        backLabel.setForeground(new java.awt.Color(255, 255, 255));
        backLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        backLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(backLabel)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, -1, -1));

        menu.add(jPanel4, java.awt.BorderLayout.CENTER);

        add(menu, java.awt.BorderLayout.LINE_START);

        userProcessContainer.setBackground(new java.awt.Color(199, 247, 247));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        add(userProcessContainer, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonLabelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeButtonLabelMouseClicked

    private void closeButtonLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonLabelMouseEntered
        // TODO add your handling code here:
        colorChangeOnClick(CloseButton, new Color(204, 0, 0));
    }//GEN-LAST:event_closeButtonLabelMouseEntered

    private void closeButtonLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonLabelMouseExited
        // TODO add your handling code here:
        colorChangeOnClick(CloseButton, new Color(15, 29, 52));
    }//GEN-LAST:event_closeButtonLabelMouseExited

    private void maxButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxButtonLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_maxButtonLabelMouseClicked

    private void maxButtonLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxButtonLabelMouseEntered
        // TODO add your handling code here:
        colorChangeOnClick(CloseButton, new Color(0, 237, 0));
    }//GEN-LAST:event_maxButtonLabelMouseEntered

    private void maxButtonLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxButtonLabelMouseExited
        // TODO add your handling code here:
        colorChangeOnClick(CloseButton, new Color(204, 0, 0));
    }//GEN-LAST:event_maxButtonLabelMouseExited

    private void hideMenuButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMenuButtonLabelMouseClicked
        // TODO add your handling code here:
        menuClickHandling(hidemenu, hidemenu, 1);
        if (index == true) {
            showHideMenuHandling(menu, index, hideMenuButtonLabel);
            SwingUtilities.updateComponentTreeUI(this);
            index = false;
        } else {
            showHideMenuHandling(menu, index, hideMenuButtonLabel);
            SwingUtilities.updateComponentTreeUI(this);
            index = true;
        }
    }//GEN-LAST:event_hideMenuButtonLabelMouseClicked

    private void hideMenuButtonLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMenuButtonLabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_hideMenuButtonLabelMouseEntered

    private void hideMenuButtonLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMenuButtonLabelMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_hideMenuButtonLabelMouseExited

    private void profileButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileButtonLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_profileButtonLabelMouseClicked

    private void manageRequestsButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_manageRequestsButtonLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_manageRequestsButtonLabelMouseClicked

    private void backLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backLabelMouseClicked
        // TODO add your handling code here:
        JFrame frame = (JFrame) getWindowAncestor(this);
        frame.dispose();
        dB4OUtil.storeSystem(ecoSystem);
    }//GEN-LAST:event_backLabelMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BtnMax;
    private javax.swing.JPanel ButtonMinMaxClose;
    private javax.swing.JPanel CloseButton;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel backLabel;
    private javax.swing.JLabel closeButtonLabel;
    private javax.swing.JLabel hideMenuButtonLabel;
    private javax.swing.JPanel hidemenu;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel linehidemenu;
    private javax.swing.JLabel manageRequestsButtonLabel;
    private javax.swing.JLabel maxButtonLabel;
    private javax.swing.JPanel menu;
    private javax.swing.JPanel menuIcon;
    private javax.swing.JLabel profileButtonLabel;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
