/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UserInterface.CareSystemCoordinatorRole;

import HealthCentre.DB4OUtil.DB4OUtil;
import HealthCentre.EcoSystem;
import HealthCentre.Enterprise.Enterprise;
import HealthCentre.Network.Network;
import HealthCentre.Organization.CareSystemCoordinatorOrganisation;
import HealthCentre.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import static javax.swing.SwingUtilities.getWindowAncestor;

/**
 *
 * @author romiltiwari
 */
public class SystemCoordinatorWorkAreaJPanel extends javax.swing.JPanel {

    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();
    private UserAccount userAccount;
    boolean index = true;
    private CareSystemCoordinatorOrganisation careSystemCoordinatorOrg;
    private Enterprise enterprise;
    private EcoSystem ecoSystem;
    private DonorDirectory donorDirectory;
    private Network network;

    /**
     * Creates new form SystemCoordinatorWorkAreaJPanel
     */
    public SystemCoordinatorWorkAreaJPanel(UserAccount userAccount,
            CareSystemCoordinatorOrganisation careSystemCoordinatorOrg,
            Enterprise enterprise, EcoSystem ecoSystem, Network network) {
        initComponents();
        this.userAccount = userAccount;
        this.careSystemCoordinatorOrg = careSystemCoordinatorOrg;
        this.enterprise = enterprise;
        this.ecoSystem = ecoSystem;
        this.network = network;
    }

    /**
     * Description : Color Change on Click Handling
     *
     * @param jPanel
     * @param randomColor
     */
    public void colorChangeOnClick(JPanel jPanel, Color randomColor) {
        jPanel.setBackground(randomColor);
    }

    /**
     * Description : Handle Menu Click
     *
     * @param hidePanel1
     * @param hidePanel2
     * @param number
     */
    public void menuClick(JPanel hidePanel1, JPanel hidePanel2, int number) {
        if (number == 1) {
            hidePanel1.setBackground(new Color(70, 55, 37));
            hidePanel2.setBackground(new Color(216, 99, 1));
        } else {
            hidePanel1.setBackground(new Color(216, 99, 1));
            hidePanel2.setBackground(new Color(70, 55, 37));
        }
    }

    /**
     * Description : Change Image on Click Handling
     *
     * @param labelButton
     * @param resourceImage
     */
    public void imageChangeOnClick(JLabel labelButton, String resourceImage) {
        ImageIcon aimg = new ImageIcon(getClass().getResource(
                resourceImage));
        labelButton.setIcon(aimg);
    }

    /**
     * Description : Menu Hide/Show Handling on Click event.
     *
     * @param showHideMenu
     * @param board
     * @param labelButton
     */
    public void showHideMenuHandling(JPanel showHideMenu, boolean board, JLabel labelButton) {
        if (board == true) {
            showHideMenu.setPreferredSize(new Dimension(50,
                    showHideMenu.getHeight()));
            imageChangeOnClick(labelButton, "/Images/menu_32px.png");
        } else {
            showHideMenu.setPreferredSize(new Dimension(270,
                    showHideMenu.getHeight()));
            imageChangeOnClick(labelButton, "/Images/menu_32px.png");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainHeader = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        closeButton = new javax.swing.JPanel();
        closeButtonLabel = new javax.swing.JLabel();
        maximizeButton = new javax.swing.JPanel();
        maxButtonLabel = new javax.swing.JLabel();
        sideTabMenu = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        linehidemenu = new javax.swing.JPanel();
        hidemenu = new javax.swing.JPanel();
        hideMenuButton = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        organDonorListButton = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        receivingPatientListButton = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        organDonorRequestButton = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        managePatientRequestButton = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        userProfileButton = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        backButton = new javax.swing.JLabel();
        userProcessContainer = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        MainHeader.setBackground(new java.awt.Color(15, 29, 52));
        MainHeader.setPreferredSize(new java.awt.Dimension(800, 50));
        MainHeader.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(150, 50));

        closeButton.setBackground(new java.awt.Color(15, 29, 52));
        closeButton.setPreferredSize(new java.awt.Dimension(50, 50));

        closeButtonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        closeButtonLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete_32px.png"))); // NOI18N
        closeButtonLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        closeButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeButtonLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                closeButtonLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                closeButtonLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout closeButtonLayout = new javax.swing.GroupLayout(closeButton);
        closeButton.setLayout(closeButtonLayout);
        closeButtonLayout.setHorizontalGroup(
            closeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(closeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(closeButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );
        closeButtonLayout.setVerticalGroup(
            closeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(closeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(closeButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        maximizeButton.setBackground(new java.awt.Color(15, 29, 52));
        maximizeButton.setPreferredSize(new java.awt.Dimension(50, 50));

        maxButtonLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        maxButtonLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/full_screen_32px.png"))); // NOI18N
        maxButtonLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        maxButtonLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                maxButtonLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                maxButtonLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                maxButtonLabelMouseExited(evt);
            }
        });

        javax.swing.GroupLayout maximizeButtonLayout = new javax.swing.GroupLayout(maximizeButton);
        maximizeButton.setLayout(maximizeButtonLayout);
        maximizeButtonLayout.setHorizontalGroup(
            maximizeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(maximizeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(maxButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );
        maximizeButtonLayout.setVerticalGroup(
            maximizeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(maximizeButtonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(maxButtonLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 961, Short.MAX_VALUE)
                .addComponent(maximizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maximizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        MainHeader.add(jPanel1, java.awt.BorderLayout.CENTER);

        add(MainHeader, java.awt.BorderLayout.PAGE_START);

        sideTabMenu.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(50, 500));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        linehidemenu.setBackground(new java.awt.Color(15, 29, 52));
        linehidemenu.setPreferredSize(new java.awt.Dimension(50, 5));

        javax.swing.GroupLayout linehidemenuLayout = new javax.swing.GroupLayout(linehidemenu);
        linehidemenu.setLayout(linehidemenuLayout);
        linehidemenuLayout.setHorizontalGroup(
            linehidemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        linehidemenuLayout.setVerticalGroup(
            linehidemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel2.add(linehidemenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 10));

        hidemenu.setBackground(new java.awt.Color(15, 29, 52));
        hidemenu.setPreferredSize(new java.awt.Dimension(50, 50));

        hideMenuButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        hideMenuButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back_32px.png"))); // NOI18N
        hideMenuButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hideMenuButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hideMenuButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hideMenuButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hideMenuButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout hidemenuLayout = new javax.swing.GroupLayout(hidemenu);
        hidemenu.setLayout(hidemenuLayout);
        hidemenuLayout.setHorizontalGroup(
            hidemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
            .addGroup(hidemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(hidemenuLayout.createSequentialGroup()
                    .addComponent(hideMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        hidemenuLayout.setVerticalGroup(
            hidemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(hidemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(hideMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE))
        );

        jPanel2.add(hidemenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, -1));

        sideTabMenu.add(jPanel2, java.awt.BorderLayout.LINE_START);

        jPanel3.setBackground(new java.awt.Color(31, 31, 31));
        jPanel3.setPreferredSize(new java.awt.Dimension(220, 500));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(31, 31, 31));

        organDonorListButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        organDonorListButton.setForeground(new java.awt.Color(255, 255, 255));
        organDonorListButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        organDonorListButton.setText("Donors List");
        organDonorListButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        organDonorListButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                organDonorListButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(organDonorListButton, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel9Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(organDonorListButton, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 220, 50));

        jPanel10.setBackground(new java.awt.Color(31, 31, 31));

        receivingPatientListButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        receivingPatientListButton.setForeground(new java.awt.Color(255, 255, 255));
        receivingPatientListButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        receivingPatientListButton.setText("Patients(Recievers) List");
        receivingPatientListButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        receivingPatientListButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                receivingPatientListButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(receivingPatientListButton, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(receivingPatientListButton, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel3.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, -1));

        jPanel11.setBackground(new java.awt.Color(31, 31, 31));

        organDonorRequestButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        organDonorRequestButton.setForeground(new java.awt.Color(255, 255, 255));
        organDonorRequestButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        organDonorRequestButton.setText("Manage Donor Requests");
        organDonorRequestButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        organDonorRequestButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                organDonorRequestButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(organDonorRequestButton, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel11Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(organDonorRequestButton, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel3.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, -1));

        jPanel12.setBackground(new java.awt.Color(31, 31, 31));
        jPanel12.setForeground(new java.awt.Color(31, 31, 31));

        managePatientRequestButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        managePatientRequestButton.setForeground(new java.awt.Color(255, 255, 255));
        managePatientRequestButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        managePatientRequestButton.setText("Manage Patient Requests");
        managePatientRequestButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        managePatientRequestButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                managePatientRequestButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(managePatientRequestButton, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel12Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(managePatientRequestButton, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel3.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, -1, -1));

        jPanel13.setBackground(new java.awt.Color(31, 31, 31));

        userProfileButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        userProfileButton.setForeground(new java.awt.Color(255, 255, 255));
        userProfileButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        userProfileButton.setText("Profile");
        userProfileButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        userProfileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userProfileButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel13Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(userProfileButton, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel13Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(userProfileButton, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel3.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, -1, -1));

        jPanel14.setBackground(new java.awt.Color(31, 31, 31));

        backButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(backButton)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, -1, -1));

        sideTabMenu.add(jPanel3, java.awt.BorderLayout.CENTER);

        add(sideTabMenu, java.awt.BorderLayout.LINE_START);

        userProcessContainer.setBackground(new java.awt.Color(199, 247, 247));
        userProcessContainer.setLayout(new java.awt.CardLayout());
        add(userProcessContainer, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void closeButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonLabelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_closeButtonLabelMouseClicked

    private void closeButtonLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonLabelMouseEntered
        // TODO add your handling code here:
        colorChangeOnClick(closeButton, new Color(204, 0, 0));
    }//GEN-LAST:event_closeButtonLabelMouseEntered

    private void closeButtonLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeButtonLabelMouseExited
        // TODO add your handling code here:
        colorChangeOnClick(closeButton, new Color(15, 29, 52));
    }//GEN-LAST:event_closeButtonLabelMouseExited

    private void maxButtonLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxButtonLabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_maxButtonLabelMouseClicked

    private void maxButtonLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxButtonLabelMouseEntered
        // TODO add your handling code here:
        colorChangeOnClick(maximizeButton, new Color(0, 237, 0));
    }//GEN-LAST:event_maxButtonLabelMouseEntered

    private void maxButtonLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_maxButtonLabelMouseExited
        // TODO add your handling code here:
        colorChangeOnClick(closeButton, new Color(15, 29, 52));
    }//GEN-LAST:event_maxButtonLabelMouseExited

    private void hideMenuButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMenuButtonMouseClicked
        // TODO add your handling code here:

        menuClick(hidemenu, hidemenu, 1);
        if (index == true) {
            showHideMenuHandling(sideTabMenu, index,
                    hideMenuButton);
            SwingUtilities.updateComponentTreeUI(this);
            index = false;
        } else {
            showHideMenuHandling(sideTabMenu, index,
                    hideMenuButton);
            SwingUtilities.updateComponentTreeUI(this);
            index = true;
        }
    }//GEN-LAST:event_hideMenuButtonMouseClicked

    private void hideMenuButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMenuButtonMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_hideMenuButtonMouseEntered

    private void hideMenuButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hideMenuButtonMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_hideMenuButtonMouseExited

    private void organDonorListButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_organDonorListButtonMouseClicked
        // TODO add your handling code here:
        OrganDonorListJPanel organDonorListJPanel = new OrganDonorListJPanel(userAccount, ecoSystem, network);
        userProcessContainer.add("OrganDonorListJPanel", organDonorListJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_organDonorListButtonMouseClicked

    private void receivingPatientListButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_receivingPatientListButtonMouseClicked
        // TODO add your handling code here:
        PatientListJPanel patientListJPanel = new PatientListJPanel(userAccount, ecoSystem, network, careSystemCoordinatorOrg);
        userProcessContainer.add("PatientListJPanel", patientListJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_receivingPatientListButtonMouseClicked

    private void organDonorRequestButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_organDonorRequestButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_organDonorRequestButtonMouseClicked

    private void managePatientRequestButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_managePatientRequestButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_managePatientRequestButtonMouseClicked

    private void userProfileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userProfileButtonMouseClicked
        // TODO add your handling code here:
        ManageSystemCoordinatorProfileJPanel manageSystCoordinatorProfile = 
                new ManageSystemCoordinatorProfileJPanel(userAccount, careSystemCoordinatorOrg, enterprise);
        userProcessContainer.add("ManageSystemCoordinatorProfile", manageSystCoordinatorProfile);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_userProfileButtonMouseClicked

    private void backButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backButtonMouseClicked
        // TODO add your handling code here:
        JFrame frame = (JFrame) getWindowAncestor(this);
        frame.dispose();

        dB4OUtil.storeSystem(ecoSystem);
    }//GEN-LAST:event_backButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainHeader;
    private javax.swing.JLabel backButton;
    private javax.swing.JPanel closeButton;
    private javax.swing.JLabel closeButtonLabel;
    private javax.swing.JLabel hideMenuButton;
    private javax.swing.JPanel hidemenu;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel linehidemenu;
    private javax.swing.JLabel managePatientRequestButton;
    private javax.swing.JLabel maxButtonLabel;
    private javax.swing.JPanel maximizeButton;
    private javax.swing.JLabel organDonorListButton;
    private javax.swing.JLabel organDonorRequestButton;
    private javax.swing.JLabel receivingPatientListButton;
    private javax.swing.JPanel sideTabMenu;
    private javax.swing.JPanel userProcessContainer;
    private javax.swing.JLabel userProfileButton;
    // End of variables declaration//GEN-END:variables
}
